### ISSUE TITLE
Update for compatibility with 5.0

### ISSUE THREAD

**Issue by RandyTobias** [JMAConsulting/biz.jmaconsulting.grantprograms#258]
This might just simply be that the info.xml needs to be updated to 4.7.

**Comment by JoeMurray** [comment]
Edsel, could you work up an estimate with Pradeep of what would be required to make this 4.7 compatible?

**Comment by Edzelopez** [comment]
There are quite a bit of changes, mainly changes to using API rather than BAO functions that were supported in 4.4. We will also need to change the install pattern and fix bugs related to changes in quickform HTML types. We also have to change many of the core overridden files that were present in 4.4 and try as far as possible to prevent overriding them in the new version. I have added an estimate which encompasses all these steps in our issue tracker.

**Comment by RandyTobias** [comment]
This isn't meant negatively in any way; I'm asking so I can learn: why would you write an extension using tools that make it difficult to update when civicrm is updated? Was it simply that the API v3 didn't have the tools available that you needed and were able to get from the bao? I've only really been writing civi code since about 4.5, but I've generally stuck to API calls to try to make my stuff future proof (until they change to API v4...). I know I've had issues with menu interaction though.

**Comment by Edzelopez** [comment]
That's exactly what happened. This extension was developed for CiviCRM 4.4 around 3-4 years back when the API wasn't as furnished as it was now. I think API v2 was in effect at that time and most of the functionality needed was derived from BAO functions and by overriding core files since hooks did not provide sufficient support.

**Comment by RandyTobias** [comment]
Ah, that makes a lot of sense then. Thank you very much for helping me to understand this. I feel it relates to one of the things I personally would like to see happen more: there is a lot of great extensions out there that are generally abandoned because the ability it update them is far more complicated than it should be. I very much would like to see tools in place (maybe this is something that api v3 has addressed) that will allow people to simply have to update their compatible with version numbers in the xml to update an extension because the framework that it was written on is still compatible with whatever the current version of civi is.

**Comment by JoeMurray** [comment]
We've been able to do that with some of our newer extensions. The estimate is to make that possible here too.

**Comment by JoeMurray** [comment]
@RandyTobias FYI we are releasing a new version when testing is completed shortly for CiviCRM v5.x. You're welcome to help with testing :)
